name: Cleanup PR artifacts

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

env:
  STACK_PREFIX: PMTDSA-${{ GITHUB_REF }}

jobs:
  deploy-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up deployment
        run: |
          echo Cleaning up stack with prefix of ${{ STACK_PREFIX }}
        shell: bash