name: Publish on changes
on:
  push:
    branches: [ main ]

env:
  TAG_PATTERN: package-

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      run_job: ${{ steps.check-step.outputs.run_job }}
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Get file changes
        id: files
        uses: jitterbit/get-changed-files@v1
      - name: Check for changed files
        id: check-step
        run: |
          for file in ${{ steps.files.outputs.all }}; do
            echo "Running check on file: ${file}"
            if [[ ${file} = .github/* ]]; then
               echo "File matches";
               echo "::set-output name=run_job::true";
               break;
            fi
          done;
        shell: bash

  publish:
    needs: [ check-for-changes ]
    if: ${{ needs.check-for-changes.outputs.run_job == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Do it
        id: do-it
        run: |
          echo "Doing the publish thing"
          export ENV=PROD
          echo Setting do it ENV=${ENV}
          echo "::set-output name=di-env::${ENV}";
        shell: bash
      - name: Do the push to npm
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo In Do the push with ENV=${{ steps.do-it.outputs.di-env }}
