name: Publish on changes
on:
  push:
    branches: [ main ]

env:
  TAG_PATTERN: package-

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Get file changes
        id: files
        uses: jitterbit/get-changed-files@v1
      - name: Check for changed files
        run: |
          for file in ${{ steps.files.outputs.all }}; do
            echo "Running check on file: ${file}"
            if [[ ${file} = .github/* ]]; then
               echo "File matches";
               echo "::set-output name=run_job::true";
               break;
            fi
          done;
        shell: bash

  publish:
    needs: [ check-for-changes ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Do it
        run: |
          echo "if: ${{ needs.check-for-changes.outputs.output1 }}"
          echo "Doing the publish thing"
        shell: bash
        
    
      - name: Do the push to npm
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
